spring:
  application:
    name: config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/1498047434/Microservice_testing_for_orderFood.git
#          username: 1498047434@qq.com
#          password: DING97836524xyyG
          basedir: /Volumes/Programming/Projects/Learn/LearnSpringCloud/config/localGitConfig
      label: config-repo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8079
