spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://152.136.127.162/order_food?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    port: 6379
    host: 152.136.127.162
    timeout: 3000
    database: 1
    password: 123456
server:
  port: 8082
env:
  dev
