eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: clientName
#    register-with-eureka: false
    ser
spring:
  application:
    name: client